security:
    encoders:
        Symfony\Component\Security\Core\User\UserInterface: auto
    providers:
        user_provider:
            id: 'App\User\Infrastructure\Bundle\Security\UserProvider'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/v1/
            provider: user_provider
            anonymous: ~
            guard:
                authenticators:
                    - App\User\Infrastructure\Bundle\Security\ApiAuthenticator
    access_control:
        - { path: ^/api/v1/auth/(security|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1/user/, roles: ROLE_USER  }
